<a href="https://colab.research.google.com/github/johcue/computational_complexity-/blob/main/sort_methods_python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd
import numpy as np
import sys

In [ ]:
!pip install ipython-autotime
%load_ext autotime

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.6/1.6 MB 39.7 MB/s eta 0:00:00
time: 446 µs (started: 2023-04-22 22:32:22 +00:00)


In [17]:
# SACAMOS LOS VECTORES
a = np.random.randint(0,500000,500000)
a = a.astype(int)
#np.savetxt("num_500e3.csv", a, delimiter=",") 

In [18]:
## Get Data from GITHUB
## NO VAYAN A ABRIR LOS CSV, SE PUEDEN TIRAR EL PC
from typing_extensions import dataclass_transform
df = pd.read_csv('https://raw.githubusercontent.com/johcue/computational_complexity-/main/num_1e6.csv',sep=',')
data = df.to_numpy()
data = np.transpose(data).astype(int)
size = len(data)
print(data)

[[1003987 6664807 7463715 ... 9665372 6194840  887679]]


In [19]:
print(np.sort(data))

[[      0      13      24 ... 9999969 9999988 9999989]]


In [ ]:
## REESCRIBIMOS EL TIEMPO DE RECURSION DEFAULT DE PYTHON
sys.setrecursionlimit(100000)

time: 355 µs (started: 2023-04-22 21:07:54 +00:00)


## Selection Sort
Selection sort method found [here](https://www.programiz.com/dsa/quick-sort)

In [20]:
#Selection Sort
def selectionSort(array, size):
   
    for step in range(size):
        min_idx = step
        
        for i in range(step + 1, size):
         
            # to sort in descending order, change > to < in this line
            # select the minimum element in each loop
            if array[i] < array[min_idx]:
                min_idx = i
         
        # put min at the correct position
        (array[step], array[min_idx]) = (array[min_idx], array[step])

selectionSort(data, size)
print('Sorted Array in Ascending Order:')
print(data)

Sorted Array in Ascending Order:
[[1003987 6664807 7463715 ... 9665372 6194840  887679]]


In [ ]:
# Quick sort in Python

# Function to find the partition position
def partition(array, low, high):
 
    # choose the rightmost element as pivot
    pivot = array[high]
 
    # pointer for greater element
    i = low - 1
 
    # traverse through all elements
    # compare each element with pivot
    for j in range(low, high):
        if array[j] <= pivot:
 
            # If element smaller than pivot is found
            # swap it with the greater element pointed by i
            i = i + 1
 
            # Swapping element at i with element at j
            (array[i], array[j]) = (array[j], array[i])
 
    # Swap the pivot element with the greater element specified by i
    (array[i + 1], array[high]) = (array[high], array[i + 1])
 
    # Return the position from where partition is done
    return i + 1
 
# function to perform quicksort
 
 
def quickSort(array, low, high):
    if low < high:
 
        # Find pivot element such that
        # element smaller than pivot are on the left
        # element greater than pivot are on the right
        pi = partition(array, low, high)
 
        # Recursive call on the left of pivot
        quickSort(array, low, pi - 1)
 
        # Recursive call on the right of pivot
        quickSort(array, pi + 1, high) 

time: 995 µs (started: 2023-04-22 21:08:14 +00:00)


In [ ]:
quickSort(data, 0, size - 1)
print('Sorted Array in Ascending Order:')
print(data)

Sorted Array in Ascending Order:
[   116    183    251 ... 999709 999903 999972]
time: 31.6 s (started: 2023-04-22 21:08:20 +00:00)
